src/objects/V1Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <label>Path</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <externalId>true</externalId>
        <label>UserName</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>V1Settings</label>
</CustomObject>

VersionOne Integration/src/classes/Settings.cls
public with sharing class Settings implements ISettings {
	private final V1Settings__c mycs;
	private final String escalateQueueId;

	public Settings () {
		User thisUser = [ Select Id from User where Id = :UserInfo.getUserId() ];

		mycs = V1Settings__c.getValues('V1Settings');

		if(mycs == null) {
			mycs = new V1Settings__c(Name= 'V1Settings');
			mycs.Path__c = 'http://localhost/VersionOne/';
			mycs.UserName__c = 'admin';
			mycs.Password__c = 'admin';
			insert mycs;
		}

		mycs.Path__c = 'http://195.62.49.62:7001/VersionOne/';


		String queueName = 'Escalate to VersionOne';
		String queueString = 'SELECT ID, Name FROM Group WHERE Name=\''+queueName+'\'' ;
		Group owner = (Group) Database.query(queueString);
		escalateQueueId = owner.Id;
	}

	public String getPath() {
		return mycs.Path__c;
	}

	public void setPath(String path) {
		mycs.Path__c = path;
	}

	public String getUserName() {
		return mycs.UserName__c;
	}

	public String getPassword() {
		return mycs.Password__c;
	}

	public String getEscalateQueueId() {
		return escalateQueueId;
	}

	public String getSource() {
		return 'SalesForce';
	}
}